prefix private shell funtions with _

diff --git a/bin/pass-man b/bin/pass-man
--- a/bin/pass-man
+++ b/bin/pass-man
@@ -18,7 +18,7 @@ timer=6h
 
 ## Usage
 ########
-usage(){
+_usage(){
     cat <<HELP
 
 pass-man v1.1.0
@@ -35,7 +35,7 @@ HELP
 
 ## Check if tomb is opened
 ##########################
-check_tomb_open(){
+_check_tomb_open(){
     if tomb list >/dev/null 2>&1; then
         return 0
     else
@@ -45,11 +45,11 @@ check_tomb_open(){
 
 ## Open vault
 #############
-vault_open(){
-    if ! check_tomb_open; then
+_vault_open(){
+    if ! _check_tomb_open; then
         pass open -f --timer="${timer}"
 
-        if ! check_tomb_open; then
+        if ! _check_tomb_open; then
             echo "Failed to open tomb." >&2
             exit 1
         fi
@@ -58,11 +58,11 @@ vault_open(){
 
 ## Close vault
 ##############
-vault_close(){
-    if check_tomb_open; then
+_vault_close(){
+    if _check_tomb_open; then
         pass close
 
-        if check_tomb_open; then
+        if _check_tomb_open; then
             echo "Failed to close tomb." >&2
             exit 1
         fi
@@ -71,8 +71,8 @@ vault_close(){
 
 ## Generate new password
 ########################
-vault_generate(){
-    vault_open
+_vault_generate(){
+    _vault_open
     pass generate -f aaa_tmp "${@}"
 }
 
@@ -81,10 +81,10 @@ vault_generate(){
 ## @param    $1  Path to password
 ## @param    $@  Extra arguments to 'pass'
 ##########################################
-vault_retrieve(){
+_vault_retrieve(){
     local path="${1?:"Path to password missing"}"
     shift
-    vault_open
+    _vault_open
     pass "${@}" "${path}"
 }
 
@@ -102,21 +102,21 @@ action="${1:-}"
 
 # Switch action
 case "${action}" in
-    open) vault_open ;;
-    close) vault_close ;;
-    generate) vault_generate "${@}" ;;
+    open) _vault_open ;;
+    close) _vault_close ;;
+    generate) _vault_generate "${@}" ;;
     retrieve)
         pass_path="${1:-}"
         if [[ -n "${pass_path}" ]]; then
             shift
         else
             echo "Path to password missing" >&2
-            usage
+            _usage
         fi
-        vault_retrieve "${pass_path}" "${@}"
+        _vault_retrieve "${pass_path}" "${@}"
         ;;
-    "") echo "Action missing" >&2 && usage ;;
-    *) echo "Invalid action" >&2 && usage ;;
+    "") echo "Action missing" >&2 && _usage ;;
+    *) echo "Invalid action" >&2 && _usage ;;
 esac
 
 exit 0
