debug tunnel

diff --git a/lib/debug b/lib/debug
--- a/lib/debug
+++ b/lib/debug
@@ -23,3 +23,57 @@ debug-dns-mail(){
     print-header "DKIM"
     dig TXT "${selector}._domainkey.${domain}"
 }
+
+# Open SSH tunnel to remote XDebug
+#
+# @param    $1  Remote host
+##################################
+debug-tunnel-open(){
+    local remote="${1?:"Missing remote"}"
+    local ssh_command="ssh -fqN -R 9003:localhost:9003 ${remote}"
+
+    # Check if already opened
+    if proc-is-running ${ssh_command}; then
+        echo "Tunnel already opened"
+        return 0
+    fi
+
+    # Open tunnel
+    ${ssh_command}
+
+    # Check if successful
+    if proc-is-running ${ssh_command}; then
+        echo "Tunnel opened"
+        return 0
+    else
+        echo "Failed to open tunnel"
+        return 1
+    fi
+}
+
+# Close SSH tunnel to remote XDebug
+#
+# @param    $1  Remote host
+###################################
+debug-tunnel-close(){
+    local remote="${1?:"Missing remote"}"
+    local ssh_command="ssh -fqN -R 9003:localhost:9003 ${remote}"
+
+    # Check if already closed
+    if ! proc-is-running ${ssh_command}; then
+        echo "Tunnel already closed"
+        return 0
+    fi
+
+    # Close tunnel
+    pkill -f "${ssh_command}"
+
+    # Check if successful
+    if proc-is-running ${ssh_command}; then
+        echo "Failed to close tunnel"
+        return 1
+    else
+        echo "Tunnel closed"
+        return 0
+    fi
+}
